# Go to Rich documentation to know about values of attributes
[panel]
border_style = "bold"
box = "HEAVY"
border_colour = "cyan1"
padding_top_right = 1
padding_bottom_left = 1
padding_top = 1
padding_right = 1
padding_bottom = 1
padding_left = 1
width = 55
height = 10

[ascii_panel]
border_style = "bold"
box = "DOUBLE"
border_colour = "magenta2"
padding_top_right = 0
padding_bottom_left = 4
padding_top = 0
padding_right = 0
padding_bottom = 4
padding_left = 4
width = 50
height = 12

[colours]
col_city = "cyan3"
col_wind = "purple2"

[colours.col_temp]
high = "red1"
mid = "yellow1"
low = "blue1"

[colours.col_humid]
high = "deep_pink1"
mid = "green1"
low = "violet"

[colours.col_desc]
Thunderstorm = "deep_sky_blue1"
Drizzle = "cyan2"
Rain = "blue_violet"
Snow = "white"
Atmosphere = "grey27"
Clear = "gold1"
Clouds = "purple3"