# Go to Rich documentation to know about values of attributes
[panel]
border_style = "bold"
box = "ROUNDED"
border_colour = "light_steel_blue"
padding_top_right = 1
padding_bottom_left = 1
padding_top = 1
padding_right = 1
padding_bottom = 1
padding_left = 1
width = 55
height = 10

[ascii_panel]
border_style = "bold"
box = "MINIMAL"
border_colour = "light_steel_blue"
padding_top_right = 0
padding_bottom_left = 8
padding_top = 0
padding_right = 0
padding_bottom = 8
padding_left = 8
width = 50
height = 12

[colours]
col_city = "light_steel_blue"
col_wind = "sky_blue1"

[colours.col_temp]
high = "sandy_brown"
mid = "chartreuse3"
low = "deep_sky_blue1"

[colours.col_humid]
high = "cornflower_blue"
mid = "green_yellow"
low = "indian_red"

[colours.col_desc]
Thunderstorm = "dodger_blue2"
Drizzle = "deep_sky_blue2"
Rain = "light_steel_blue3"
Snow = "bright_white"
Atmosphere = "grey53"
Clear = "dark_orange"
Clouds = "orchid"