# Go to Rich documentation to know about values of attributes
[panel]
border_style = "dim"             
box = "MINIMAL"                  
border_colour = "grey50"         
padding_top_right = 0            
padding_bottom_left = 0          
padding_top = 0                  
padding_right = 0                
padding_bottom = 0               
padding_left = 0                 
width = 55                       
height = 10                      

[ascii_panel]
border_style = "dim"             
box = "ASCII"                    
border_colour = "grey50"         
padding_top_right = 0            
padding_bottom_left = 4          
padding_top = 0                  
padding_right = 0                
padding_bottom = 4               
padding_left = 4                 
width = 50                       
height = 12                      

[colours]
col_city = "grey70"              
col_wind = "sky_blue3"           

[colours.col_temp]
high = "orange3"                 
mid = "green3"                   
low = "blue3"                    

[colours.col_humid]
high = "steel_blue"              
mid = "lime_green"               
low = "red3"                     

[colours.col_desc]
Thunderstorm = "blue4"           
Drizzle = "sky_blue2"            
Rain = "grey62"                  
Snow = "white"                   
Atmosphere = "grey46"            
Clear = "yellow3"                
Clouds = "purple3"               